### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by knightcube**
GlideApp doesn't work anymore. We use Glide now. So that is what should be there in the documentation

### CODE REVIEW

**Comment by knightcube** [comment]
i signed it

**Comment by Tolriq** [comment]
You might want to read better the doc ;) We do use GlideApp as you shoud be using the annotation processor to generate it ;)

**Comment by knightcube** [comment]
yes you are right. My bad :)

**Comment by knightcube** [comment]
i will close the pull request

**Pull request closed without merging**
