### PR TITLE
Fix GIF not display with EOF error

### LINKED ISSUE #1145: can not show gif image with last frame broken
this is image address:http://img1.famulei.com/z/0/p/164/2113351333687.gif.

this image cause this exception.
8lq le f 07 170miybuh

the image showed up when we deleted last frame of this gif image.

### PR DESCRIPTION
**Pull request by s1rius**
Fix #1145 
Some image urls to test:
http://img1.famulei.com/z/0/p/164/2113351333687.gif
http://7vzseb.com1.z0.glb.clouddn.com/12nuDeDV4xU3yE.gif
http://p3.pstatp.com/large/2ce000064e9f0b034f1

### CODE REVIEW

**Comment by s1rius** [comment]
I signed it!

**Comment by sjudd** [comment]
Thanks for putting this up. I'm inclined to accept this I think. Can you briefly describe the new behavior for this images? I'd imagine it will match Chrome by running through all valid frames once and then failing when it reaches an invalid frame?

The only issue I could see is that it doesn't allow the app developer to easily tell that the GIF load won't behave as they expect. We don't have a way of communicating a partial failure at the moment.

**Comment by s1rius** [comment]
Sorry for late.
With this PR, Glide will treat a damaged GIF as a normal GIF which contains some valid frames. The invalid frames will be ignored. And the valid frames will default keep looping not just run once.
If an user see a damaged GIF on web or gallery. I think, make the user see a valid GIF on an app which used Glide is better than display a placeholder image.
@sjudd

**Comment by TWiStErRob** [comment]
@sjudd when looking at the code this is what I concluded too. I guess there's no point it crashing the app when a bad image is loaded, but probably a warning log would be useful to communicate partial failure when `header.getStatus() != GifDecoder.STATUS_OK`.

@s1rius did you actually look into what's wrong with these files? Are there bytes missing from the end (partial file), or is it an encoder error, or maybe something else?

**Comment by s1rius** [comment]
@TWiStErRob I actually look into the wrong with this [file](http://7vzseb.com1.z0.glb.clouddn.com/12nuDeDV4xU3yE.gif), and I compared the bad file and the good file.The bad file lost many bytes. 
compare

**Comment by TWiStErRob** [comment]
> The only issue I could see is that it doesn't allow the app developer to easily tell that the GIF load won't behave as they expect. We don't have a way of communicating a partial failure at the moment.

@sjudd how about putting this logic behind an Option? The default would be as before in v3, but users who expect partial files (like @s1rius) can enable the option? Or the reverse: default is to decode and show everything, but strict users can disable partial decoding.

**Comment by sjudd** [comment]
Option is ok with me for now, good idea.

Ideally you'd want some partial success indicator, but I can't think of way to do that without expanding a bunch of interfaces or changing the behavior of Targets.

**Comment by s1rius** [comment]
I think decode and show everything is a good idea.

If I am an strict user, I will guarantee every GIF upload to server is good. So my App displays every GIF correctly from server.
And I want to ignore bad GIFs stored in local. But I don't know which GIF is bad before decoding it. Instead, I display a placeholder image on the bad Gif position.

**Comment by s1rius** [comment]
Maybe decode and show everything is OK.
If I am an strict developer, I will guarantee every GIF upload to server is good. So my App displays every GIF correctly from server.
And I want to ignore bad GIFs stored in local. But I don't know which GIF is bad before decoding it. Instead, I display a placeholder image on the bad Gif position in my gallery Activity. It is not make sense.
So, I think decode and show everything is a good idea.

**Comment by chenwulue** [comment]
so,how to show gif like those,them can be show by fresco or broswer

**Pull request closed without merging**
