### PR TITLE
Cross fade now respects different aspect ratio placeholder and loaded image

### PR DESCRIPTION
**Pull request by kevinvanmierlo**
This pull request will fix the aspect ratio not being respected when using the crossFade transition. This is related to issue #363

### CODE REVIEW

**Comment by kevinvanmierlo** [comment]
@googlebot I signed it!

**Comment by kevinvanmierlo** [comment]
@sjudd I've tried to fix the format violations by importing the Google Java's code style XML and adding some Javadoc, but Travis still fails. It tells me to run 'gradlew spotlessApply' but this task fails for me. So right now I'm not sure what to do to fix this.

**Comment by chaubunhtha** [comment]
Chào

**Comment by TWiStErRob** [comment]
Have you tried reading the error messages?
https://travis-ci.org/github/bumptech/glide/jobs/617859292#L1572-L1653

Spotless tells you exactly what to change, and I'm sure you can run `gradlew checkstyle pmd` to get the failures locally.

**Comment by kevinvanmierlo** [comment]
I did look at it at the time, but didn't see the error messages in between. Thanks for the link to the specific lines. This was 2.5 years ago when I did this and did it besides my job, so must've looked over it.

Okay, would be great to use spotless, but it didn't work for me at the time. I didn't know about the checkstyle command, but I'll check it out next time.

 I still do this besides my job, so I'll try to fix it as soon as I have time.

**Comment by kevinvanmierlo** [comment]
Is there anything else you need from me?

**Pull request closed without merging**
