### PR TITLE
okhttp 3.0.1

### PR DESCRIPTION
**Pull request by b95505017**

### CODE REVIEW

**Comment by TWiStErRob** [comment]
Nice :) Why did the interface needed changing? Did it change between `rc` and `.0.1`?

**Comment by b95505017** [comment]
Change between `rc` and `.0.0` :smile: 
https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-300

**Comment by swankjesse** [comment]
Thumbs up.

**Comment by b95505017** [comment]
When will this PR merged? Or should I change something?

**Comment by sjudd** [comment]
Thanks!

**Comment by b95505017** [comment]
:+1:

**Comment by guiwro** [comment]
Got this runtime error with glide ```4.0.0-SNAPSHOT``` and ```okhttp3-integration 2.0.0-SNAPSHOT```:

```java
FATAL EXCEPTION: OkHttp Dispatcher
                                                                           Process: com.myapp.android.debug, PID: 21585
                                                                           java.lang.AbstractMethodError: abstract method "void okhttp3.Callback.onResponse(okhttp3.Call, okhttp3.Response)"
                                                                               at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
                                                                               at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)
`

**Comment by b95505017** [comment]
After a little search and got this:
https://github.com/square/okhttp/issues/2248

**Comment by TWiStErRob** [comment]
See #900.

**Pull request merged**
