### PR TITLE
fix bug #2894

### PR DESCRIPTION
**Pull request by ooeoo**

### CODE REVIEW

**Comment by ooeoo** [comment]
I signed it!

**Comment by ooeoo** [comment]
I signed it!

**Comment by iBotasky** [comment]
@ooeoo Did this bug fix?
What reason course this happen?

**Comment by iBotasky** [comment]
OK

**Comment by sjudd** [comment]
I believe the underlying cause is actually that loader that we intend to load the url isn't attempted. This will just make Glide find one less loader, it won't make Glide find the right loader.

**Comment by ooeoo** [comment]
The correct loader was executed, but an error occurred, causing the next loader to be executed, but it should not be executed.

**Comment by sjudd** [comment]
The concerning cases in the referenced issue are the ones where the http loader was not executed. 

If you just want to reduce some of the guaranteed to fail load attempts you can, but it doesn't fix the referenced issue. 

If you do want the behavior you've added, then move the check for ``handles()`` into ``buildLoadData`` and return null if the wrapped loader returns `false`. That way we only  have to parse the Uri once.

**Comment by ooeoo** [comment]
You are right, it just reduce some ModelLoader.

**Comment by kozaxinan** [comment]
Do we know the core reason for this issue? Or does someone have a plan for fix?

**Pull request closed without merging**
