### PR TITLE
Fixed 3.6.0 Javadocs link

### PR DESCRIPTION
**Pull request by jush**

### CODE REVIEW

**Comment by jush** [comment]
I'm not contributing with code do I really need to sign the CLA?

**Comment by sjudd** [comment]
If you'd rather not, let me know and I can check.

**Comment by jush** [comment]
I signed it!

**Comment by jush** [comment]
@sjudd thanks. After all, I decided to sign it.

**Comment by sjudd** [comment]
Great thanks!

**Pull request merged**
