### PR TITLE
Make non-started loads are visible via Android lint

### PR DESCRIPTION
**Pull request by TWiStErRob**
## Description

Add `@CheckResult` to request builder's non-terminal methods.

## Motivation and Context

Prevent issues like https://github.com/bumptech/glide/issues/2419#issuecomment-331282358 by giving a lint error if Glide is used incorrectly. The builder must be terminated in order to start the load, so any intermediate builder methods' result must be used.

### CODE REVIEW

**Comment by TWiStErRob** [comment]
Do we want to add the annotation on terminal methods that return `FutureTarget`? As far as I know `submit()`/`submit(int,int)`/`into(int,int)` needs to be cancelled (as per class JavaDoc), this would only ensure that at least `.get()` was called, even if not `cancel`.

**Comment by sjudd** [comment]
You'll want to remove the check result special casing here too: https://github.com/bumptech/glide/blob/7457b9d82d2596c8f6be38e66cc7978d06568627/annotation/compiler/src/main/java/com/bumptech/glide/annotation/compiler/RequestBuilderGenerator.java#L312.

I'm ok with adding ``@CheckResult`` to submit if we make ``preload()`` handle being called on a background thread for users who just want to trigger a load on a background thread but don't want to do anything with a future. ``cancel()`` isn't really a requirement though, it can be an optimization if you're loading a lot of the same image type.

**Comment by TWiStErRob** [comment]
I think this is good enough without `submit()`, especially if you say `cancel()` is not required.

Re APT: not sure I understand what that check does, didn't have time to good deep into that new code.

**Comment by sjudd** [comment]
Merged here: 739cb35b637e8d4dd277d1133dbaeb2e2dc7d4ad. Thanks!

**Pull request closed without merging**
