### PR TITLE
Removed synthetic methods

### PR DESCRIPTION
**Pull request by RiteshChandnani**
## Description

This removes all the synthetic methods.
Issue #1555 
## Motivation and Context

This change helps us reduce the method count and therefore also helps us avoid the trampoline created because of synthetic methods.

### CODE REVIEW

**Comment by TWiStErRob** [comment]
Looking at the diff I think it would be a good idea to leave /*private*/ in the code and put a comment in the default constructors so that a future cleanup wouldn't reverse the changes.

How does adding a default scoped ctor help? Without a default scoped ctor (1 method) a private one is generated with an accessor (2 methods)?

**Comment by RiteshChandnani** [comment]
@TWiStErRob 
Thanks for checking my PR.
I will put a comment in default constructors to avoid cleanup. But, I can't get my arms around - " I think it would be a good idea to leave /private/ in the code", can you please elaborate a bit more.

And, yes, if we don't have a default scoped ctor, two ctors will be synthesized, one will be the private constructor with no params and one will be a package private constructor with an arbitrary param (its type is dependent on compiler implementation, and hence one addtional empty class to support ctor overloading.
I also made a dummy implementation and used reflection and found the same.

Sorry, due to different timezones I was unable to get back to you immediately.

**Comment by TWiStErRob** [comment]
> I think it would be a good idea to leave `/*private*/` in the code

If you look at this code out of context, what you see is that one of the fields are non-private for seemingly no reason (all usages of it are within the same class).

```java
  private final Glide glide;
  final Lifecycle lifecycle;
  private final RequestTracker requestTracker;
```

This would make it more clear that it was supposed to be private, but cannot due to some limitation.
```java
  private final Glide glide;
  /*private*/ final Lifecycle lifecycle;
  private final RequestTracker requestTracker;
```
potentially an even better approach would be a `@PreventSynthetic` or `@Private` source-level annotation to prevent thinking of commenting out as a forget-to-revert-after-debug thing.

Actually, thinking of it, isn't there a library out there which does this automatically? I mean if there is a way to have lambdas in Java 5, some APT code should be able to increase visibility of fields.

**Comment by RiteshChandnani** [comment]
Got it.
So, we can have a `@PreventSynthetic` source-level annotation to make the code more clear.

Like this one:
https://github.com/hidroh/materialistic/blob/master/app/src/main/java/io/github/hidroh/materialistic/annotation/Synthetic.java

So, I can go forward and implement that source-level annotation and update the code accordingly?

Yeah, there should be a library which does this automatically, but I was unable to find something after doing a quick search.

**Comment by TWiStErRob** [comment]
Yep, that example looks good, hidroh/materialistic#642 is where it was introduced.

So the changes are:
```diff
-   private final Type name;
+   @Synthetic final Type name;
```
I like the shorter `@Synthetic` name. Annotate the constructors as well, then they can be left empty.

**Comment by TWiStErRob** [comment]
Btw, don't know what @sjudd's stand is on this, I hope he'll accept, but not sure.

**Comment by RiteshChandnani** [comment]
Great.
Will do it right away!

Yeah, even I hope the same about that.

**Comment by RiteshChandnani** [comment]
Btw, I think we should create a new directory named "annotation" in "glide/library/src/main/java/com/bumptech/glide/" 

What's your take?

**Comment by RiteshChandnani** [comment]
Also, `diskLruCache` is a git submodule, can I go and update that one too?

**Comment by TWiStErRob** [comment]
Yes, you can contribute to `disklrucache` as well, it's http://github.com/sjudd/disklrucache that you need to fork. You need two separate PRs (this and another) and you can't depend on code in each other (i.e. the annotation). As far as I remember the cache doesn't have many classes, so it should be less likely to have synthetics.

I would put the annotation in library/src/main/java/com/bumptech/glide/util, because it's not part of the public API.

**Comment by RiteshChandnani** [comment]
@TWiStErRob 
Got it.
Thanks!
I will first finish with this PR and later look into `disklrucache`.

Will move the annotation directory under `library/src/main/java/com/bumptech/glide/util`

**Comment by RiteshChandnani** [comment]
No worries. I will fix it.

**Comment by TWiStErRob** [comment]
You can run `gradlew checkstyle pmd` to see the problems.

You'll likely need `@SuppressWarnings("PMD.SpecificViolationName")` on the constructors, or try to modify the PMD config if it's possible to suppress the violations when the `Synthetic` annotation is present.

**Comment by RiteshChandnani** [comment]
All checks passed locally, but I used `@SuppressWarnings("PMD.UncommentedEmptyConstructor")` rather than changing PMD config because I don't know much about writing custom PMD rules.

What's your take?
Can I go forward and push that code?

**Comment by TWiStErRob** [comment]
Why suppress if you can write a comment inside? Suppressions usually need to be explained, but if there's a comment, it explains itself.

I don't know much either, but based on a quick research it's quite simple. I found this: http://pmd.sourceforge.net/pmd-5.1.1/howtowritearule.html and the source for the rule is https://github.com/pmd/pmd/blob/master/pmd-java/src/main/resources/rulesets/java/design.xml#L1401-L1431 . I don't have time right now, but it looks like it should be as easy as adding `and not(hasAnnotation(....Synthetic))` (`junit.xml` has examples of how you can do the `hasAnnotation` part). Since `xpath` is just a property I think it could be overridden like `allowCommentedBlocks` in `<glide>/library/pmd-ruleset.xml`.

I say if you have time or curious go ahead with changing the rule, if not, just go with comments.

**Comment by RiteshChandnani** [comment]
No worries, I will give it a try!
Thanks Robert!

**Comment by TWiStErRob** [comment]
Nice. Just noticed something: the samples are not part of the API, they're just usage examples. I think it's better to keep synthetics there, so they're more portable (copy-paste).

**Comment by RiteshChandnani** [comment]
Thanks a lot Robert!
So, I will remove synthetics from samples.

**Comment by TWiStErRob** [comment]
Thanks :) Now, we just have to wait for @sjudd to ack.

Note: there are some weird new-lines left in diff
https://github.com/bumptech/glide/pull/1556/files#diff-4fdac1e84ca614a23bd46483d941e644

**Comment by RiteshChandnani** [comment]
Yeah, no worries.

I will remove those weird lines.

**Comment by TWiStErRob** [comment]
I think you misunderstood me there, I mean that there are some 1-line changes where the change is just inserting a new line without any other change:
image

The import groups should be separated by a new line, and Checkstyle/PMD may fail on this.

**Comment by TWiStErRob** [comment]
No, but I mostly saw them in samples after your last push removing code from those. I suggest you squash your commits locally first, then amend the last commit to see if there are irrelevant modifications in the squashed diff. We would squash-merge anyway, so it doesn't matter that the commits are lost.

**Comment by RiteshChandnani** [comment]
Btw, `I mean that there are some 1-line changes where the change is just inserting a new line without any other change`

I have to just double sure that you mean to say that I have to get rid of that new line, right?

**Comment by TWiStErRob** [comment]
If there's no related change (like adding/removing an import or method), then there should no random whitespace changes in the diff either. So, yes, make sure any standalone added/removed newline is not in the diff, especially in files with no other changes.

**Comment by RiteshChandnani** [comment]
Btw, looking at the original source files I found that grouping is not applied in imports. Hence, to maintain consistency across the project I think I should also follow the same path.

**Comment by TWiStErRob** [comment]
Huh, that's interesting. Here's the commit that added groups: https://github.com/bumptech/glide/commit/f7a6d65cf7c1a41908dd48e0dab68ee5b881387e, but you're right the current code doesn't have groups, and that's because of https://github.com/bumptech/glide/commit/3f5543a1519e2b711a677f9072ad56734f492f86. This is a recent change, I haven't been following the `master` branch closely enough. So ,no separation. I wonder how Sam formatted the code... it looks like [the import order in settings](https://github.com/bumptech/glide/blob/master/.idea/codeStyleSettings.xml#L22-L256) wasn't updated to reflect the style.

**Comment by RiteshChandnani** [comment]
Yeah! You are right too!

**Comment by TWiStErRob** [comment]
The current diff looks good, sorry about the confusion.

**Comment by RiteshChandnani** [comment]
No worries at all Robert!

I was honored to work on this!
Was not aware about PMD before this, now will go back and update my projects!

Thanks a lot! :)

**Comment by sjudd** [comment]
Thanks for putting this together!

Can you do a quick before/after on the class/method count to verify the changes?

**Comment by RiteshChandnani** [comment]
Yeah Sam here it is -

Before count: 54
After count: 3

**Comment by TWiStErRob** [comment]
Huh, what's that 3 remaining?

**Comment by RiteshChandnani** [comment]
But why Flag is not being raised by the IDE for these :/

screenshot from 2016-10-31 21-40-54

**Comment by TWiStErRob** [comment]
IDEA/AS is not perfect, they are always working to make them better, just check out the [EAP release notes](https://confluence.jetbrains.com/display/IDEADEV/IDEA+2016.3+EAP). I reported [quite a few myself](https://youtrack.jetbrains.com/issues?q=created%20by:%20TWiStErRob%20) the latest one being what you just found: https://youtrack.jetbrains.com/issue/IDEA-163379

**Comment by RiteshChandnani** [comment]
Ohh!
Thanks!
I was able to bring that down to 0 by making annotating those variables as `@Synthetic`

**Comment by TWiStErRob** [comment]
Yep, the class file is what matters in the end, IDE warnings just helpers. Don't forget to commit and push the changes ;)

**Comment by RiteshChandnani** [comment]
Yeah! Will do it right away! :+1:

**Comment by RiteshChandnani** [comment]
After analyzing both versions of dex files I found total method count as -

Before: 3282
After: 3202

**Comment by RiteshChandnani** [comment]
I found class count as -

Before: 470
After: 456

**Comment by sjudd** [comment]
LGTM, Thanks!

I wonder if it's possible to write a build check for this?

**Comment by RiteshChandnani** [comment]
@sjudd 

I am thankful to you too for writing such a great library! :)

`I wonder if it's possible to write a build check for this?`
Even I am musing about the same..

**Comment by TWiStErRob** [comment]
I think PMD works on class files, so we can check if they have `access\$\d\d[02]` methods.

**Comment by TWiStErRob** [comment]
@RiteshChandnani bug you found with sibling-synthetics is fixed already.

**Comment by RiteshChandnani** [comment]
Yeah I checked too!
https://youtrack.jetbrains.com/issue/IDEA-16337

Nice that it has been fixed fixed! :)
Thanks Robert! :+1:

**Pull request merged**
