### PR TITLE
support cronet net library whose version is 79.0.3945.79

### PR DESCRIPTION
**Pull request by bgylde**

### CODE REVIEW

**Comment by sjudd** [comment]
Sorry for the delay here. We actually have an internal version of a cronet integration that I'd be happy to open source. My main issue is that I haven't had the chance to figure out how to build cronet externally.

Where did you get the cronet files? Did you build them yourself?

**Comment by sjudd** [comment]
Ok to answer my own question, there are a few versions of cronet available on maven: https://mvnrepository.com/artifact/org.chromium.net. However the recommended way to do depend on cronet is via gms core: https://developer.android.com/guide/topics/connectivity/cronet/start

**Comment by bgylde** [comment]
> Sorry for the delay here. We actually have an internal version of a cronet integration that I'd be happy to open source. My main issue is that I haven't had the chance to figure out how to build cronet externally.
> 
> Where did you get the cronet files? Did you build them yourself?

Yes, I compiled the cronet myself. Souce code was from chromium.

**Comment by bgylde** [comment]
> Ok to answer my own question, there are a few versions of cronet available on maven: https://mvnrepository.com/artifact/org.chromium.net. However the recommended way to do depend on cronet is via gms core: https://developer.android.com/guide/topics/connectivity/cronet/start

I had ever tried the play-services-cronet, but it has to depend on the google service. Or I can delete the cronet jar and so, just use the compileOnly way.

**Comment by sjudd** [comment]
Replaced by #4404

**Pull request closed without merging**
