### PR TITLE
Update IntelliJ code style settings to follow existing style

### PR DESCRIPTION
**Pull request by SUPERCILEX**
From discussion: https://github.com/bumptech/glide/pull/2670#issuecomment-348802398.

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
@sjudd In the end, I've left the java imports be since I think it's just alphabetical coincidence that they end up at the bottom most of the time.

**Comment by sjudd** [comment]
The import style should be:

All static imports in alphabetical order
empty line
All non-static imports in alphabetical order

And that looks like what you have in this file.

But since most imports start with com, yeah I'd guess java is probably further down the list usually.

**Comment by SUPERCILEX** [comment]
Yep, that's what I left it at. 😄

**Comment by sjudd** [comment]
Awesome thanks!

**Pull request merged**
