### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by Dimous**
## Description
Changed dependancy to official google repository.

## Motivation and Context

mcxiaoke's mirror for volley is deprecated

### CODE REVIEW

**Comment by Dimous** [comment]
I signed it!

**Comment by TWiStErRob** [comment]
Where is this getting the jar from? I can't find it in jcenter or maven central. Is it in the Android SDK?

**Comment by Dimous** [comment]
https://bintray.com/android/android-utils/com.android.volley.volley/view

**Comment by FabianTerhorst** [comment]
@Dimous volley version is 1.0.16, but the version from bintray is 1.0.0.

**Comment by TWiStErRob** [comment]
@FabianTerhorst, yes, they changed the group I'd, so they restarted counting.
See https://github.com/mcxiaoke/android-volley's README.md

**Comment by FabianTerhorst** [comment]
@Dimous when you change the version inside to gradle.properties file to 1.0.0 travis should build.

**Comment by TWiStErRob** [comment]
Oh, I see. That change should be in this PR ás well.

**Comment by TWiStErRob** [comment]
@Dimous thanks, it likely won't pass though because we have a problem with Robolectric, out of scope for this PR.

**Comment by sjudd** [comment]
Thanks!

**Comment by TWiStErRob** [comment]
@sjudd this has a side effect:
```gradle
compile 'com.github.bumptech.glide:volley-integration:2.0.0-SNAPSHOT'
```
> Error: Module 'com.github.bumptech.glide:volley-integration:2.0.0-SNAPSHOT' depends on one or more Android Libraries but is a jar

```
+--- com.github.bumptech.glide:volley-integration:2.0.0-SNAPSHOT
|    +--- com.android.volley:volley:1.0.0
|    \--- com.github.bumptech.glide:glide:4.0.0-SNAPSHOT (*)
\--- com.mcxiaoke.volley:library:1.0.19
```

The old dep was distributed as both AAR and JAR: http://repo1.maven.org/maven2/com/mcxiaoke/volley/library/1.0.19/
The new dep is just AAR:
https://bintray.com/android/android-utils/com.android.volley.volley/view#files/com/android/volley/volley/1.0.0

As a workaround users can apply this:
```gradle
compile('com.github.bumptech.glide:volley-integration:2.0.0-SNAPSHOT') {
	// exclude to prevent "depends on one or more Android Libraries but is a jar", but still depend on it below
	exclude group: 'com.android.volley', module: 'volley'
}
compile 'com.android.volley:volley:1.0.0'
```

**Pull request merged**
