### PR TITLE
Use AndroidX instead of the support library

### PR DESCRIPTION
**Pull request by sjudd**

### CODE REVIEW

**Comment by sjudd** [comment]
Fixes #3184.

However I can't submit this internally for the time being. I'm not going to block 4.9 on this.

**Comment by TWiStErRob** [comment]
Nice one! Did a quick skim, does this mean the next 4.x release will break apps using non-androidx fragments, or a start of 5.x series?

**Comment by CaiJingLong** [comment]
When will this PR merge into the main branch?
When will the AndroidX version be released?

**Comment by DusilB** [comment]
I'm also interested in when this will reach the main branch, Will the AndroidX version of Glide be ready soon?

**Comment by BladeF** [comment]
Since the stale bot closed this, when can we expect to see this PR merged?

**Comment by TWiStErRob** [comment]
I don't think it was meant to be closed, but I don't know timeline.

**Comment by mikehc** [comment]
Any updates on this issue? This is blocking my project from fully migrate to AndroidX.

**Comment by sjudd** [comment]
Sorry for the delay. The internal migration at Google is progressing somewhat slower than hoped. My only other option is to use scripting to convert back and forth when code is imported/exported, which is non-trivial and I haven't yet had the chance to get to. 

I also need to change the tool I use to run migrations to copybara (released publicly). Fortunately it appears as though someone has already written the migrations to/from androidx internally, so I may be able to kill two birds with one stone. That's my current plan. 

I am curious as to how this is blocking anyone. I was under the impression that jetifier relieves most of these issues?

**Comment by mikehc** [comment]
@sjudd in my case I'm using a custom glide module to register my own instance of OkHttpClient. The generated code used android support library imports. And I think in some classes they were using imports for both AndroidX and Support Library.

It's been a while since I tried making the migration so I don't have the code at hand.

**Comment by wbervoets** [comment]
Also looking forward to having Glide depending on AndroidX. The Jetifier task does take build time, not ? Apart from play-services-location this is the only one still depending on the old support libraries in the app I'm working on.

**Pull request closed without merging**
