### PR TITLE
Fix some typo in docs

### PR DESCRIPTION
**Pull request by Muyangmin**
## Description

I've forked Glide v4 repo to translate gh-pages into Simplified Chinese language on 06/08, based on revision [#17d5b1a](https://github.com/bumptech/glide/commit/17d5b1ae365cc6d4603fb5352ac2de9a5a15e223). In the pass days I've finished translation, also find some typos in the doc and fixed them in my repo.

Today I fetched bumptech repo again, and found those typos in `sample.md` and `transitions.md` are all fixed by [this commit](https://github.com/bumptech/glide/commit/6bd90044a5879b4216a89ea139af05e85e0b96ca). **But in the `generatedapi.md`, there are still 2 place to be modified** (*strictly not typo, but not match article context as I think,* see [this commit](https://github.com/bumptech/glide/commit/43d6f4590b50ca411e8c34122fe158329e644e78)).

I would be very happy if this PR can be merged 😃

### CODE REVIEW

**Comment by Muyangmin** [comment]
I've signed the CLA, but not sure whether all fields are correctly provided.

**Comment by sjudd** [comment]
Sorry for the hassle, but I can't find a cla for the email address in your patch here. Did you maybe sign it with a different email?

Thanks for putting this, I'd definitely like to merge it. I'm also curious about the translation. Are you planning on hosting it somewhere? Or is it for internal usage?

**Comment by Muyangmin** [comment]
Maybe I've signed using a wrong email address, since my GitHub public email and git commit `user.email` is currently end with **foxmail.com**, while I signed using Gmail account. *When I signed it I recognized it seems impossible to using a non-gmail account to sign-in Google Developers website, so I filled my foxmail account as the contact information.* Now it seems not work, should I change github user to gmail or do anything else?

The translation version is totally for open source, I'd like to host it on GitHub Pages. Unfortunately my current home computer is using Windows OS, there seems to be some compatibility issues with ruby and gems, so I'm not really preferred to use Jekyll. Instead I prepared to use **[Hexo](https://github.com/hexojs/hexo)**, and maybe still need a few days to adjust themes.

However, if glide official docs repo decide to provide multi-language support, I'm very glad to provide those translation articles.

**Comment by Muyangmin** [comment]
I've changed CLA `GitHub Account Name` field value:
* before: my GitHub email (name end with @xx.com)
* now:  my GitHub account (name with no suffix)

Sorry for bringing inconvenience for you, but I'm really the first time to sign cla for myself. If This still not work, maybe I need some help.

**Comment by sjudd** [comment]
Looks like the change you made did it, thanks for bearing with us on this!

I'm definitely interested in translations, let me take a little bit and look in to what I can do and I'll try and get back to you. Thanks for the info.

**Pull request merged**
