### PR TITLE
Add GlideModule for lazily initialization.

### LINKED ISSUE #299: Reduce Glide setup time
Currently it seems like it can take up to 30ms. We should consider ways to reduce that time or at least allow ModelLoaders to be registered lazily. Branching from @TWiStErRob in #295:

```
Normal startup (5 samples):
TIMING﹕ Glide.get: 15.87, Glide.register: 0.09, new Client: 0.70, new Factory: 0.12
TIMING﹕ Glide.get: 16.60, Glide.register: 0.09, new Client: 0.76, new Factory: 0.15
TIMING﹕ Glide.get: 20.78, Glide.register: 0.12, new Client: 1.10, new Factory: 0.21
TIMING﹕ Glide.get: 23.38, Glide.register: 0.12, new Client: 1.07, new Factory: 0.21
TIMING﹕ Glide.get: 31.86, Glide.register: 0.18, new Client: 5.16, new Factory: 0.34

with Start Method Tracing:
TIMING﹕ Glide.get: 64.97, Glide.register: 0.82, new Client: 2.47, new Factory: 0.40
```

### PR DESCRIPTION
**Pull request by sjudd**
Fixes #299.

### CODE REVIEW

**Comment by TWiStErRob** [comment]
Concern: metadata without a value looks strange.
Wouldn't it be better if you did `name="com.bumptech.glide.module.flickr" value="full.class.name"`, less parsing (no need for substring, but you can keep the startswith check) and better readability, compliance.
The doc for metadata.name says to prefix your name with package: http://developer.android.com/guide/topics/manifest/meta-data-element.html

**Comment by sjudd** [comment]
@TWiStErRob The reason why the fully qualified class name has to be in the key is that there can be only one metadata tag for a given key. If we use anything other than the fully qualified class name, it's possible a user would accidentally try to add two different implementations with the same key (two different classes in the same package for example). If they did so, we'd have no way to detect the error because the manifest merger/parser would silently merge the two.

I agree the syntax is funky, but unless there's some way around the fully qualified class name issue, I'm not sure we have anything useful to put in the value.

**Comment by TWiStErRob** [comment]
Note that I still left flicker in the name, which is just a random name. That name after that is not used anywhere just helps readability, users can organize modules nicer. E.g. for okhttp it would be different, the point is to start it with `...glidemodule.`.
I read the design doc lately and as I remember the merger will conflict if two modules have the same name after glidemodule, but the values are different.
The best would be a multivalued metadata which is not supported sadly.

**Comment by TWiStErRob** [comment]
Also in case of placeholders (e.g. I hate duplicating the package name so I have a placeholder for it like `${packageName}.subpackage.Class`) it's cleaner to start with that instead of having it in the middle.

**Comment by sjudd** [comment]
We've actually tried something like this with user specifiable names, and found that people would still occasionally choose the same name. Using the class name just completely eliminates the possibility, unless they add the same class twice, in which case ignoring the second copy should be fine.

We could drop ``glidemodule:`` altogether, but then we wouldn't be able to assert as much (malformed class name and failing to implement GlideModule would have to be ok). 

We could append :glidemodule instead if you think that's cleaner?

**Comment by sjudd** [comment]
Another option would be to leave the fully qualified class name as the key, but set glidemodule as the value. Maybe that's cleaner? It would at least avoid the string parsing.

**Comment by TWiStErRob** [comment]
Hmm that's interesting... just realized: all of these are hacks, so I guess the last one is the best of them you're taking onto consideration.

Rant follows :) Your response to people occasionally choosing the same names is the approach I saw at my university in the classes following my year, a lot of students were failing the most basic programming tests so they made them easier every semester. My view/approach is always: use stuff as designed, so keys as keys and value as values. End of rant.

**Comment by sjudd** [comment]
I hear you. It's worth keeping in mind though that it's not even necessarily possible for people to do the right thing. If you have a number of independent library projects, each owned by separate teams, and multiple of those teams define their own modules, we don't want to force people to go inspect all of the other team's modules before they come up with a module name (or keep a list of all used names somewhere...). 

I agree it's the best of bad options, I'll move module into the value and remove the prefix.

**Comment by sjudd** [comment]
Made the change, PTAL, thanks for the input!

**Comment by sjudd** [comment]
I added documentation about manifest merging, hopefully I got it right (having not done this in gradle before...)

**Comment by kxs109** [comment]
I have a question, I want to load some imgs include gif from the net and list in the listview, it is ok and amazing to show, i like the performance,  but it's bad when run the app the first time after install it, it will take a long time to show these imgs. i don't know why...

**Comment by TWiStErRob** [comment]
Please open a new question to follow up, also see https://github.com/bumptech/glide/blob/master/CONTRIBUTING.md#filing-issues

**Pull request merged**
