### PR TITLE
Improve Kotlin support for RecyclerView module

### PR DESCRIPTION
**Pull request by SUPERCILEX**
@sjudd Alrighty, round one! 😄

I'm basically going around all my libraries and adding nullability annotations everywhere to improve Kotlin type inference. This PR adds nullability annotations to the recycler view module and its dependencies.

PS: about the commits in this PR, I noticed that you rebased my previous PR. Would you like me to cleanup these commits or are you fine squashing this PR?

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
@sjudd It looks like the [IntelliJ code style](https://github.com/bumptech/glide/blob/master/.idea/codeStyleSettings.xml) is out of date. Can you commit the latest one you're using so I can get my imports formatted correctly? Thanks!

**Comment by sjudd** [comment]
Re the code style: http://bumptech.github.io/glide/dev/contributing.html#code-style.

We could either update to that style, which risks it getting out of date again, or we could delete it and just push people to the google style.

**Comment by SUPERCILEX** [comment]
@sjudd I think it' easier to just update the IntelliJ code style to what you already use so I've created #2674.

**Comment by sjudd** [comment]
In terms of rebasing/squashing you're welcome to do whatever you'd like. If there are commits you don't think should be squashed let me know, but usually I default to squashing/rebasing when I accept the PR. 

You definitely don't need to keep the PR rebased on top of unrelated non-conflicting changes, that's just tedious.

**Comment by SUPERCILEX** [comment]
@sjudd SGTM! I'm usually lazy with my PR commits so I'd lean towards squashing if I were you. 😄

**Comment by SUPERCILEX** [comment]
Whoops, didn't notice the build was failing.

**Comment by sjudd** [comment]
Thanks!

**Pull request merged**
