### PR TITLE
Fix circle crop rect bug.

### PR DESCRIPTION
**Pull request by start141**
I found circleCrop have a bug.
please see below:

9a34a35e-9dcd-11e5-8498-76459d4fd1da 1

the reslut
70ed6fa4-3867-4cbd-a8fb-3590fe8e190c

### CODE REVIEW

**Comment by start141** [comment]
I signed it!

**Comment by TWiStErRob** [comment]
Can you please fix the code (or tests) and squash into one commit?

**Comment by start141** [comment]
I will try to fix it again tomorrow. @TWiStErRob

**Comment by start141** [comment]
`Because the expected result is a circle image, so I adjust the
transformed bitmap as the same edge(use the min edge).`

With the ImageView scaleTyle, it can bring more layout style(center, start or end).

**Comment by sjudd** [comment]
Squashed, rebased, and merged here: https://github.com/bumptech/glide/commit/3db87601f7c577317e63e4123fb348b0e8736f93

Thanks!

**Pull request closed without merging**
