### PR TITLE
Update to Gradle 5.6.4

### PR DESCRIPTION
**Pull request by EwoutH**
## Description
Updates the Gradle Wrapper to version 5.6.4

## Motivation and Context
Updating Gradle ensures that the latest warnings and depreciation messages are included. It also improves build speed.

Part of #4482.

### CODE REVIEW

**Review by kanelbulle — CHANGES_REQUESTED** [review]
Thanks for the change!

The checksum for the gradle-wrapper.jar does not match any known checksums of gradle releases. I think you might have built the wrapper without using the upgraded gradle version. See https://docs.gradle.org/current/userguide/gradle_wrapper.html#troubleshooting_a_checksum_mismatch for more info on how to correct this.

**Comment by EwoutH** [comment]
Are you sure? The Gradle Wrapper Validation action reports:
```
Found known Gradle Wrapper JAR files:
3dc39ad650d40f6c029bd8ff605c6d95865d657dbfdeacdb079db0ddfffedf9f gradle/wrapper/gradle-wrapper.jar
```

**Comment by kanelbulle** [comment]
You're right, I didn't see that! I was comparing manually with the published SHAs. Sorry about that & thanks for the change!

**Review by benju69 — APPROVED** [review]

**Review by kanelbulle — APPROVED** [review]

**Comment by kanelbulle** [comment]
Apologies for the delay! Had to get this approved internally.

**Comment by EwoutH** [comment]
No worries, thanks the effort and merging!

**Pull request merged**
