### PR TITLE
Cleanup target api annotations

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Any reason to use `TargetApi`? Dunno why the support lib folks haven't just deprecated that annotation, but `RequiresApi` is the better one. Also, this PR removes target annotations for api 14 which is the min of this library anyway.

### CODE REVIEW

**Comment by sjudd** [comment]
I think most of these are actually not correct.

``@RequiresAPI`` means it's up to the caller to only call the method/class if they're on that API level or higher. 
``@TargetAPI`` means that the method/class is certifying that it's safe for it to be used on any API level, as long as the internal methods use APIs less than or equal to the specified target API.

In most of these cases the methods themselves are checking the SDK version, so we should be using ``@TargetApi``.

**Comment by SUPERCILEX** [comment]
Ohhh, I see what you're saying. Then is there a reason to have them at all? Every method could be annotated going by that philosophy... I'm fine either way so if you want to keep them, I'll update this PR to just remove the ones using API 14.

**Comment by sjudd** [comment]
``@TargetApi`` is basically ``@SuppressWarnings`` for API checks, except that it's limited to a maximum sdk version so that it doesn't silently suppress warnings for a newer API level if you modify the method later on to use a new sdk level that you're not checking against.

For example if we use a method that requires android O, check it properly with an if/else, suppress the warning with @SuppressWarnings, and then go back and add a method that requires O MR1, we won't see a lint or ide warning about the unsafe O MR1 call. TargetApi fixes that by warning for all methods past whatever level you give it.

So using @TargetApi makes sense whenever @SuppressWarnings would make sense, it's just a bit safer.

**Comment by sjudd** [comment]
... Also ``@SuppressWarnings`` is a user on GitHub, wups...

**Comment by SUPERCILEX** [comment]
@sjudd Ohhhhhhh, wow, that's super cool! Ok, I really get it now, yeah, that sounds awesome. Now I have to go through all my projects and remove my `@SuppressLint("NewApi")`! 😆

Anyway, I'm going to change this PR to just remove the outdated suppressions.

**Comment by SUPERCILEX** [comment]
Ok, I think I've got everything done right. I removed some checks that just seemed unnecessary, removed the API 14 ones, and changed some of the `TargetApi`s to `RequiresApi`s where relevant.

**Pull request merged**
