### PR TITLE
Option to ignore exif orientation

### PR DESCRIPTION
**Pull request by emarc-m**
## Description

This PR adds an option to request for ignoring the `EXIF` orientation parsing in `Downsampler`.  

## Motivation and Context

Addresses: https://github.com/bumptech/glide/issues/665. For some applications (like ours), the application keeps track of the orientation not stored as the EXIF data.

### CODE REVIEW

**Comment by emarc-m** [comment]
@googlebot I signed it!

**Comment by sjudd** [comment]
I don't believe it's possible to respect this flag with the new ImageDecoder library? If it is, can you update https://github.com/bumptech/glide/blob/3d54ef50ea4fa41694695971b7d858435c784057/library/src/main/java/com/bumptech/glide/load/resource/ImageDecoderResourceDecoder.java#L39.

**Comment by emarc-m** [comment]
> I don't believe it's possible to respect this flag with the new ImageDecoder library? If it is, can you update
> 
> https://github.com/bumptech/glide/blob/3d54ef50ea4fa41694695971b7d858435c784057/library/src/main/java/com/bumptech/glide/load/resource/ImageDecoderResourceDecoder.java#L39
> 
> .

Thanks for the comment @sjudd. You are correct that this could not be enforced with `ImageDecoder`.  Do you have a suggestion on how to proceed with this?

**Comment by sjudd** [comment]
I don't have any good ideas. If it can't be done with ImageDecoder, it's probably best not to expose the option for BitmapFactory. We're (slowly) moving towards ImageDecoder in Glide and it wouldn't surprise me if the framework continues to do the same.

**Comment by emarc-m** [comment]
I understand. I'll close the PR. Thanks for your help taking a look at this.

**Pull request closed without merging**
