### PR TITLE
Before draw bitmap, check bitmap was recycled.

### PR DESCRIPTION
**Pull request by ZeroBrain**
sometimes glide occured exception as java.lang.IllegalArgumentException

exception message

```
GlideBitmapDrawable.java line 101 in GlideBitmapDrawable.draw()
Cannot draw recycled bitmaps
```

so add checking bitmap was recycled.

I reviewed GifDrawable.java. it was checked recycle state.
so add same one to GlideBitmapDrawable.java

### CODE REVIEW

**Comment by TWiStErRob** [comment]
Hmm, isn't this just hiding another bug? (covering the symptom)

I thought `draw` is called on the UI thread, and so does `recycle` so they should be ordered and the target be cleared as soon as (or even before) recycle happens, i.e. draw cannot be called with an invalid bitmap.

What makes this invariant not true?

**Comment by ZeroBrain** [comment]
maybe it's hiding another bug.
but sometimes glide' lrubitmappool remove drawing bitmap.
especially low memory device was occurred frequency.
my crash was occured almost by Glide' `Cannot draw recycled bitmaps`.

GifDrawable is checked recycled or not.
but GlideBitmapDrawable isn't checked.

I thought it's more critical than hiding bug.

**Comment by sjudd** [comment]
Yes this is hiding another bug. We should not be recycling resources that are still in use. The lifecycle is roughly:

1. Decode bitmap in background
2. Pass Bitmap to Target on main thread and draw it.
3. Clear Target (or view) by either calling Glide.clear() or starting a new load into the same Target (or view). 
4. Return Bitmap to pool (and go back to #1).

If you are starting multiple loads into the same view or otherwise retaining a Bitmap after starting a new load or clearing an old load, you will see this exception. If you want to load multiple images, you need to make sure they're either loaded into separate Targets (or views), or that you avoiding using any loaded resources after a new load is started or the Target is cleared.

Probably worth [filing a new issue][1] with whatever issue you're seeing so we can look in to it.

[1]: https://github.com/bumptech/glide/issues/new?body=**Glide%20Version/Integration%20library%20(if%20any)**:%0A**Device/Android%20Version**:%0A**Issue%20details/Repro%20steps**:%0A%0A**Glide%20load%20line**:%0A%60%60%60%0AGlide.with(context)...%3B%0A%60%60%60%0A%0A**Stack%20trace**:%0A%60%60%60%0Apaste%20stack%20trace%20here%0A%60%60%60

**Comment by ZeroBrain** [comment]
@sjudd 
ah~ I understand. I guess multiple loading point in my app.

It need to add wiki or some info page.
someone may suffer about it, too

**Comment by TWiStErRob** [comment]
@sjudd do you know why the gif check is there? Just to see the whole picture here.

@ZeroBrain you can click the link at the end of Sam's comment and describe your circumstances, so we can help figure out if it's a bug in Glide or you're using it incorrectly.

**Comment by sjudd** [comment]
@TWiStErRob Git blame says: https://github.com/bumptech/glide/issues/202. GifDrawable switches back and forth between two targets on each frame but doesn't really handle when a single frame fails to load.

A better fix would be to re-use the same Target twice in a row if a single frame fails to load, so the GIF would drop a frame rather than briefly stop drawing at all.

**Comment by sjudd** [comment]
@ZeroBrain I added an article to the wiki, hope it helps: https://github.com/bumptech/glide/wiki/Resource-re-use-in-Glide

**Comment by mufumbo** [comment]
How you guys are able to fix this? I have a super simple ListView and call glide for each reused row. 

From the wiki article, it seems that I have to be responsible to not call glide again if the user is scrolling super fast on the ListView and a row is being overwritten by another load?

**Comment by mufumbo** [comment]
Also, do you guys know why this exception doesn't happen on lollipop? It happens always on 4.1.

**Pull request closed without merging**
