### PR TITLE
Deprecate Fragments

### PR DESCRIPTION
**Pull request by jaredsburrows**
Closes https://github.com/bumptech/glide/issues/2883

@sjudd

### CODE REVIEW

**Comment by sjudd** [comment]
Thanks! Would you mind adding an ``@deprecated`` javadoc to the public methods you deprecated with an explanation of what users should use instead? Might even be helpful to link to the post you mentioned in the issue that indicates that non-support fragments will be deprecated.

**Comment by sjudd** [comment]
I think you're also missing suppressions to avoid spurious deprecation warnings in Glides code. It looks like I inadvertently removed -Werror. I'll re-enable that so you'll see exactly where the suppressions are needed.

**Comment by jaredsburrows** [comment]
I agree. Let me fix.

On Feb 9, 2018 7:24 AM, "Sam" <notifications@github.com> wrote:

I think you're also missing suppressions to avoid spurious deprecation
warnings in Glides code. It looks like I inadvertently removed -Werror.
I'll re-enable that so you'll see exactly where the suppressions are needed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bumptech/glide/pull/2886#issuecomment-364464407>, or mute
the thread

**Comment by jaredsburrows** [comment]
Odd. Github says there is only 1 commit but it shows you committed 1 commit. I can't seem to pull the latest from my own branch?

**Comment by jaredsburrows** [comment]
@sjudd How do I append `@deprecated Use method {@link #with(Fragment)} instead.`? It automatically adds `@Deprecated` but not the comment.

**Comment by sjudd** [comment]
```java
/**
  * @deprecated use xyz
  */
@Deprecated
public RequestManager with(...) {
...
}
```

Is that what you're asking?

Also sorry for the build breakage, I believe I've fixed it, but if not I'll get it done tonight.

**Comment by jaredsburrows** [comment]
@sjudd I tried locally but the `GlideApp.java` auto generated for the test removes the `@deprecated use xyz`.

**Comment by sjudd** [comment]
Ah, to fix the annotation processor tests, see http://bumptech.github.io/glide/dev/contributing.html#annotation-processor-tests

**Comment by jaredsburrows** [comment]
@sjudd Every time I run `gradlew :annotation:compiler:test:test` or `gradlew :annotation:compiler:test:regenerateTestResources` it removes `@deprecated Use method {@link #with(Fragment)} instead.`.

**Comment by sjudd** [comment]
Are you modifying the generated files? Or the source? You shouldn't be changing GlideRequests, or GlideRequest directly.

**Comment by jaredsburrows** [comment]
@sjudd I am not. I am trying to change `GlideApp`. See here: https://github.com/bumptech/glide/pull/2886/files#diff-f20041aac0f70f043e9b2b81facbeb37R121.

When the tests run, it removes the `@deprecated` that you want.

**Comment by sjudd** [comment]
Removes it from where? 

If you just run the regenerate command I linked above, it should update the existing test resource files including the one you linked to match the actual output of the annotation processor.

**Comment by jaredsburrows** [comment]
@sjudd That is what I am saying. I have manually edited `GlideApp` but it does not get added to the test resources when running `gradlew :annotation:compiler:test:regenerateTestResources`.

**Comment by sjudd** [comment]
GlideApp is a generated class, like GlideRequests/GlideRequest, you shouldn't be modifying it directly. The generated one is based on Glide.java and the test resource files will be updated when you run that gradle command.

**Comment by jaredsburrows** [comment]
Sure. Look at `Glide.java` that I edited. When I run `gradlew :annotation:compiler:test:regenerateTestResources` it removes `@deprecated Use method {@link #with(Fragment)} instead.`. 

See:

screen shot 2018-02-11 at 10 08 15 am

To follow your instructions, I went ahead and just pushed up the changes.

**Comment by sjudd** [comment]
Yeah that's expected. If you want to modify the generated javadoc, you'd need modify the annotation processor directly. Probably just `@see` is sufficient.

**Comment by jaredsburrows** [comment]
@sjudd This next error is a checkstyle error. I did not add any code, only comments. I am not sure what you want me to do here.

**Comment by sjudd** [comment]
The error message is printed in travis:

  ```
 /home/travis/build/bumptech/glide/integration/recyclerview/src/main/java/com/bumptech/glide/integration/recyclerview/RecyclerViewPreloader.java
╔════════════╤══════════════════════════════════════════════════════════════╤══════════╤══════╤═════════════════════════════════════════════════╗
  ║ Reporter   │ Rule                                                         │ Severity │ Line │ Message                                         ║
  ╠════════════╪══════════════════════════════════════════════════════════════╪══════════╪══════╪═════════════════════════════════════════════════╣
  ║ Checkstyle │ com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck │ ERROR    │ 66   │ Line is longer than 100 characters (found 135). ║
  ╚════════════╧══════════════════════════════════════════════════════════════╧══════════╧══════╧═════════════════════════════════════════════════╝
```

**Comment by jaredsburrows** [comment]
@sjudd Sorry I was not feeling well. Should be all green now!

**Comment by sjudd** [comment]
Merged: 29d481ccdc8a0f0d7135359d970de071f73b6922 and 99229725401d5777e059da7b6331134bf73fbcdf. 

Thanks!

**Pull request closed without merging**
