### PR TITLE
Add nullability annotations to library module (1/n)

### PR DESCRIPTION
**Pull request by SUPERCILEX**
Man this is painful! 😄 Here's what I got done before I ran out of podcasts.

### CODE REVIEW

**Comment by SUPERCILEX** [comment]
@sjudd I couldn't find docs on updating the generated API tests. Could you help me fix those? Thanks! 😄

**Comment by sjudd** [comment]
I need to write a script for them. Right now the best way I've found to do it is to run the tests in Android Studio, then click on the failure comparison. That will open a pretty useful window that shows the complete files and highlights the diff. If the diff looks reasonable you can copy/paste the new version into the old file.

It's a pain :/. There's probably a better way of doing this...

**Comment by sjudd** [comment]
Oh I should also note that the files that we check against are stored in resources, here: https://github.com/bumptech/glide/tree/dc12b60c8f0a21eb9b3ab2164471c93d2e20ae25/annotation/compiler/test/src/test/resources.

Either the tests will have an identically named package under resources with their test classes (if their output differs from the default) or they default to the files in either https://github.com/bumptech/glide/tree/dc12b60c8f0a21eb9b3ab2164471c93d2e20ae25/annotation/compiler/test/src/test/resources/EmptyAppGlideModuleTest or https://github.com/bumptech/glide/tree/dc12b60c8f0a21eb9b3ab2164471c93d2e20ae25/annotation/compiler/test/src/test/resources/EmptyLibraryGlideModuleTest.

The helper class defines methods that are used to determine the actual path:
https://github.com/bumptech/glide/blob/dc12b60c8f0a21eb9b3ab2164471c93d2e20ae25/annotation/compiler/test/src/test/java/com/bumptech/glide/annotation/compiler/test/Util.java#L15

**Comment by SUPERCILEX** [comment]
@sjudd Ok! After trying to figure it out off and on, I think I finally got it. See #2703 😄

**Comment by sjudd** [comment]
Awesome thanks, sorry for the delay!

**Comment by SUPERCILEX** [comment]
No problemo, I haven't had time to work on the next batch anyway.

**Pull request merged**
