### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by liangricha**

### CODE REVIEW

**Comment by TWiStErRob** [comment]
Wow, nice! :) Did the IDE (IDEA?) highlight these or you hunted them down by reading?

**Comment by liangricha** [comment]
@TWiStErRob  thanks! I noticed a few while reading, and decided to hunt down all that I could using the IDE.

Do I need to add a test to make the coverage subjob pass?

**Comment by TWiStErRob** [comment]
Nah, it's -0% change. Just ignore it, we can still merge with failed builds. Once Sam see this he'll merge.

**Comment by sjudd** [comment]
Thanks!

**Pull request merged**
